"""
Generates a pre-configured MQL5 Expert Advisor file for a specific user.
The EA is embedded with the user's API key and the server URL so they
just drag-and-drop it into MT5 — no manual configuration needed.
"""

_EA_TEMPLATE = r'''//+------------------------------------------------------------------+
//|                                           RainX_Scalper.mq5     |
//|                          Generated by Raina AI — raina-ai.com   |
//|  IMPORTANT: Do not share this file — it contains your API key.  |
//+------------------------------------------------------------------+
#property copyright "Raina AI"
#property version   "1.30"
#property description "RainX automated scalping EA. Polls Raina AI for signals and executes trades automatically."

//--- Inputs (pre-filled — do not change unless told to)
input string   API_KEY         = "{{API_KEY}}";
input string   SERVER_URL      = "{{SERVER_URL}}";
input int      POLL_INTERVAL   = 30;    // seconds between signal polls
input double   DEFAULT_LOT     = 0.01;  // fallback lot size if backend doesn't specify
input int      MAGIC_NUMBER    = 77777;
input bool     ENABLE_TRADING  = true;

//--- Globals
datetime g_last_poll      = 0;
datetime g_last_heartbeat = 0;
int      g_poll_interval  = POLL_INTERVAL;
int      g_hb_interval    = 30;

//+------------------------------------------------------------------+
//| Helpers                                                          |
//+------------------------------------------------------------------+
string HttpGet(string url) {
    char   result[];
    string headers;
    char   post[];
    string req_headers = "Content-Type: application/json\r\n";
    int    timeout     = 15000;
    int    res         = WebRequest("GET", url, req_headers, timeout, post, result, headers);
    if (res == -1) {
        Print("[RainX] GET failed: ", url, " err=", GetLastError());
        return "";
    }
    return CharArrayToString(result, 0, WHOLE_ARRAY, CP_UTF8);
}

string HttpPost(string url, string body) {
    char   post[];
    char   result[];
    string headers;
    string req_headers = "Content-Type: application/json\r\n";
    int    timeout     = 15000;
    StringToCharArray(body, post, 0, StringLen(body), CP_UTF8);
    ArrayResize(post, ArraySize(post) - 1);
    int res = WebRequest("POST", url, req_headers, timeout, post, result, headers);
    if (res == -1) {
        Print("[RainX] POST failed: ", url, " err=", GetLastError());
        return "";
    }
    return CharArrayToString(result, 0, WHOLE_ARRAY, CP_UTF8);
}

//+------------------------------------------------------------------+
//| Send account heartbeat to backend                                |
//+------------------------------------------------------------------+
void SendHeartbeat() {
    double bal    = AccountInfoDouble(ACCOUNT_BALANCE);
    double eq     = AccountInfoDouble(ACCOUNT_EQUITY);
    string broker = AccountInfoString(ACCOUNT_COMPANY);
    string server = AccountInfoString(ACCOUNT_SERVER);
    long   login  = AccountInfoInteger(ACCOUNT_LOGIN);
    string mode   = AccountInfoInteger(ACCOUNT_TRADE_MODE) == ACCOUNT_TRADE_MODE_DEMO ? "demo" : "real";

    string body = StringFormat(
        "{\"api_key\":\"%s\",\"balance\":%.2f,\"equity\":%.2f,"
        "\"broker_name\":\"%s\",\"account_number\":\"%d\",\"account_mode\":\"%s\"}",
        API_KEY, bal, eq, broker, login, mode
    );
    string resp = HttpPost(SERVER_URL + "/mt5/ea/heartbeat", body);
    if (StringLen(resp) > 0)
        Print("[RainX] Heartbeat sent — balance=", DoubleToString(bal, 2), " ", mode);
}

//+------------------------------------------------------------------+
//| Poll for pending orders and execute them                         |
//+------------------------------------------------------------------+
void PollAndExecute() {
    string url  = SERVER_URL + "/mt5/ea/poll/" + API_KEY;
    string resp = HttpGet(url);
    if (StringLen(resp) == 0) return;

    // Parse orders array — lightweight string search (no JSON lib needed)
    // Expected format: {"orders":[{"id":N,"asset":"EURUSD","direction":"BUY","lot_size":0.01,...},...]}
    int start = StringFind(resp, "\"orders\"");
    if (start == -1) return;

    // Iterate over order objects
    int pos = StringFind(resp, "{", start + 8);
    while (pos != -1) {
        int end = StringFind(resp, "}", pos);
        if (end == -1) break;
        string order = StringSubstr(resp, pos, end - pos + 1);

        long   order_id  = ExtractLong(order,   "\"id\":");
        string asset     = ExtractStr(order,     "\"asset\":");
        string direction = ExtractStr(order,     "\"direction\":");
        double lot       = ExtractDouble(order,  "\"lot_size\":");
        double sl        = ExtractDouble(order,  "\"stop_loss\":");
        double tp        = ExtractDouble(order,  "\"take_profit\":");
        if (lot <= 0) lot = DEFAULT_LOT;

        if (order_id > 0 && StringLen(asset) > 0 && ENABLE_TRADING) {
            ExecuteOrder(order_id, asset, direction, lot, sl, tp);
        }
        pos = StringFind(resp, "{", end + 1);
    }
}

//+------------------------------------------------------------------+
//| Execute a single market order                                    |
//+------------------------------------------------------------------+
void ExecuteOrder(long order_id, string asset, string direction, double lot, double sl, double tp) {
    ENUM_ORDER_TYPE order_type = (direction == "BUY") ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;

    MqlTradeRequest  req = {};
    MqlTradeResult   res = {};
    req.action    = TRADE_ACTION_DEAL;
    req.symbol    = asset;
    req.volume    = lot;
    req.type      = order_type;
    req.price     = (order_type == ORDER_TYPE_BUY)
                        ? SymbolInfoDouble(asset, SYMBOL_ASK)
                        : SymbolInfoDouble(asset, SYMBOL_BID);
    req.sl        = (sl > 0) ? sl : 0;
    req.tp        = (tp > 0) ? tp : 0;
    req.magic     = MAGIC_NUMBER;
    req.comment   = "RainX|" + IntegerToString(order_id);
    req.deviation = 20;

    bool ok = OrderSend(req, res);
    if (ok && res.retcode == TRADE_RETCODE_DONE) {
        Print("[RainX] Trade OPEN: ", asset, " ", direction, " lot=", lot, " ticket=", res.order);
        // Confirm to backend
        string body = StringFormat(
            "{\"api_key\":\"%s\",\"order_id\":%d,\"success\":true,"
            "\"mt5_ticket\":%d,\"open_price\":%.5f}",
            API_KEY, order_id, res.order, res.price
        );
        HttpPost(SERVER_URL + "/mt5/ea/confirm", body);
    } else {
        Print("[RainX] Trade FAILED: ", asset, " ", direction, " retcode=", res.retcode);
        string body = StringFormat(
            "{\"api_key\":\"%s\",\"order_id\":%d,\"success\":false,\"error\":\"%d\"}",
            API_KEY, order_id, res.retcode
        );
        HttpPost(SERVER_URL + "/mt5/ea/confirm", body);
    }
}

//+------------------------------------------------------------------+
//| Report any newly closed positions                                |
//+------------------------------------------------------------------+
void ReportClosedTrades() {
    HistorySelect(TimeCurrent() - 3600, TimeCurrent());
    int total = HistoryDealsTotal();
    for (int i = 0; i < total; i++) {
        ulong ticket = HistoryDealGetTicket(i);
        if (ticket == 0) continue;
        if (HistoryDealGetInteger(ticket, DEAL_MAGIC) != MAGIC_NUMBER) continue;
        if (HistoryDealGetInteger(ticket, DEAL_ENTRY) != DEAL_ENTRY_OUT) continue;

        double profit      = HistoryDealGetDouble(ticket,  DEAL_PROFIT);
        double close_price = HistoryDealGetDouble(ticket,  DEAL_PRICE);
        long   mt5_ticket  = HistoryDealGetInteger(ticket, DEAL_POSITION_ID);

        string body = StringFormat(
            "{\"api_key\":\"%s\",\"mt5_ticket\":%d,"
            "\"close_price\":%.5f,\"profit\":%.2f}",
            API_KEY, mt5_ticket, close_price, profit
        );
        HttpPost(SERVER_URL + "/mt5/ea/close", body);
    }
}

//+------------------------------------------------------------------+
//| String extraction utilities                                      |
//+------------------------------------------------------------------+
long ExtractLong(string s, string key) {
    int p = StringFind(s, key);
    if (p == -1) return 0;
    return StringToInteger(StringSubstr(s, p + StringLen(key), 20));
}
double ExtractDouble(string s, string key) {
    int p = StringFind(s, key);
    if (p == -1) return 0;
    return StringToDouble(StringSubstr(s, p + StringLen(key), 20));
}
string ExtractStr(string s, string key) {
    int p = StringFind(s, key);
    if (p == -1) return "";
    int q = StringFind(s, "\"", p + StringLen(key) + 1);
    int r = StringFind(s, "\"", q + 1);
    if (q == -1 || r == -1) return "";
    return StringSubstr(s, q + 1, r - q - 1);
}

//+------------------------------------------------------------------+
//| EA lifecycle                                                     |
//+------------------------------------------------------------------+
int OnInit() {
    Print("[RainX] EA started. API_KEY=", StringSubstr(API_KEY,0,8), "... SERVER=", SERVER_URL);
    // Allow WebRequest to the Raina AI server
    // MT5 > Tools > Options > Expert Advisors > Allow WebRequest for listed URL:
    //   {{SERVER_URL}}
    EventSetTimer(1);
    SendHeartbeat();
    return INIT_SUCCEEDED;
}

void OnDeinit(const int reason) {
    EventKillTimer();
    Print("[RainX] EA stopped. reason=", reason);
}

void OnTimer() {
    datetime now = TimeCurrent();
    if (now - g_last_heartbeat >= g_hb_interval) {
        g_last_heartbeat = now;
        SendHeartbeat();
    }
    if (now - g_last_poll >= g_poll_interval) {
        g_last_poll = now;
        PollAndExecute();
        ReportClosedTrades();
    }
}

void OnTick() {} // Not tick-based — all logic runs on timer
//+------------------------------------------------------------------+
'''


def generate_ea(api_key: str, server_url: str) -> str:
    """Return the MQL5 EA source code pre-filled with the user's API key."""
    return _EA_TEMPLATE.replace("{{API_KEY}}", api_key).replace("{{SERVER_URL}}", server_url)
